### ISSUE TITLE
Добавить возможность регистрироваться на сайте

### ISSUE THREAD

**Issue by bronislav** [ruby-course-may-2014/reading_journal#1]
Пользователь должен иметь возможность зарегистрироваться на сайте и впоследствии использовать логин (емайл) и пароль для входа на сайт.

Также необходимо создать одну публичную страничку. Эта страница должна называться домашняя страница или как-то похоже. И одну приватную (доступную только залогининым пользователям) страничку.

**Comment by KudryashovAV** [comment]
Все сделал. Напомни, пожалуйста, как мне обновить исходный репозиторий.

**Comment by bronislav** [comment]
Вот ссылки на информацию, о том как создавать пул-реквесты:
https://help.github.com/articles/creating-a-pull-request
https://help.github.com/articles/using-pull-requests

**Comment by bronislav** [comment]
Реализовано в #2
